---
- hosts: all
  become: true
  vars:
    container_count: 4
    default_container_name: docker
    default_container_image: ubuntu
    default_container_command: sleep 1
  roles:
    - docker
    - role: explorer
      tags:
        - explorer
